src/components/Input.jsx
=> Add input component

package-lock.json, package.json, src/components/CodeView.jsx
=> Create code view

src/components/math/BoolToolBar.jsx
=> 11 boolean toolbar

src/app/layout.js, src/components/Card.jsx, src/components/Input.jsx, src/components/Navigation.jsx, src/data/navigation.js
=> progress on navbar

package-lock.json, package.json, src/components/algorithm/BinaryTree.jsx
On iPhone 12 Pro:
On desktop:
* Implements #23 
* Adds two packages:  "@visx/gradient": "^3.3.0", "@visx/hierarchy": "^3.3.0",
Props:
* `arr`: Array of strings used for nodes. Use `null` to specify a missing child. For example, Node 1 in [1, 2, null, 3, 4] has a missing child, but Node 2 has two children.
* `widthAdjust`: Proportionally adjusts the weight
* `heightAdjust`: Proportionally adjusts the height
* `nodeSize`: Sets node radius (size)
* `fontSize`: Sets font size used in node
=> Implement binary tree component

src/components/Footer.jsx
* Made footer visually better on mobile
=> Footer Mobile Responsive

src/components/algorithm/ArrayToolbar.jsx
https://github.com/acm-ucr/r-tools/assets/100977309/84c3207a-fe1b-4920-91c8-7664abb36010
Tool bar UI created
=> Created the toolbar

src/app/page.js
=> Add no search results prompt

src/app/page.js, src/components/math/Equations.jsx
=> 22 equations

src/components/Header.jsx, src/components/math/BoolToolBar.jsx, src/components/math/BoolWrapper.jsx
* Implements #36 
* Not mobile responsive (can fix if necessary)
* Only takes in `title` prop
=> Bool Wrapper

src/components/Navigation.jsx
=> Dropshadow added

src/app/math/truth-tables/page.js, src/components/math/Equations.jsx, src/components/math/TruthTable.jsx
* Resolves #51 
* Takes in an array `booleanEquations` for booleanEquations and an object `symbols` for boolean operators
* Invalid boolean equations will get evaluated to "ERROR"
=> Truth Table Component and Page

src/app/algorithm/quick-sort/page.js, src/util/sort/quickSort.js
=> Quick Sort Page

src/app/algorithm/heaps/page.js, src/util/sort/heap.js
=> Implement heap sort page

src/data/navigation.js
=> Change Icons

src/app/algorithm/bogo-sort/page.js, src/data/navigation.js, src/util/sort/bogoSort.js
=> Implement Bogo Sort

src/components/algorithm/AlgorithmWrapper.jsx, src/components/algorithm/ArrayToolbar.jsx
* Adds Step Backward button in AlgorithmWrapper
=> Step Backward

src/data/navigation.js
Page added in Nav bar. Also created a folder in /app/latex for future reference.
=> added LATEX page in nav

src/components/Table.jsx
=> Table border color fixed

src/util/sort/selectionSort.js
Updated Example Code for Selection Sort
There was an issue with the Javascript: the editor does not seem to recognize arrow functions as the arrow is highlighted in different colors, and the parenthesis surrounding the function do not match when selected on website.
=> Updated Selection Sort example code

src/app/math/truth-tables/page.js
=> Fixed default symbols bug

src/components/Input.jsx
I added a hover for the cursor to become a pointer as well since it wasn't becoming a pointer. It functions as normal
=> Clear to Div

src/components/Input.jsx, src/components/algorithm/AlgorithmWrapper.jsx
=> Added Toast Message on Play

src/components/Graph/GraphEditor.jsx, src/components/Upload.jsx
=> upload button

src/util/sort/bubbleSort.js, src/util/sort/selectionSort.js
- Updated examples for bubbleSort to include arrow functions.
- Made comment spacing consistent
- Transitioned to template literals
=> Fix Code Examples for Bubble Sort

src/app/graph/floyd-warshall/page.js, src/data/navigation.js, src/util/graph/floyd-warshall.js
=> setup Floyd Warshall

src/app/algorithm/insertion-sort/page.js, src/util/sort/insertionSort.js
=> 58 insertion sort page

src/components/Graph/GraphAlgorithm.jsx
=> Negative Edge Toast

src/app/graph/bellmen-ford/page.js, src/data/navigation.js, src/util/graph/bellmen-ford.js
1. Created Bellmen Ford Page
2. Added to navigation under category graph
3. Added header and graph algorithm component
=> Created Bellmen Ford Page

src/app/algorithm/shell-sort/page.js, src/util/sort/shellSort.js
=> 113 shell sort

src/components/ActionButton.jsx, src/components/algorithm/ArrayToolbar.jsx
Tested everything and it works perfectly and looks exactly like it was before but reduced complexity and more flexible
=> Added ActionButton

src/app/graph/bfs/page.js, src/app/graph/dijkstra/page.js, src/app/graph/floyd-warshall/page.js, src/components/Graph/GraphAlgorithm.jsx
Added weighted graph check & toast. Added props to graph pages.
=> Weighted check

src/app/graph/bellmen-ford/page.js, src/data/navigation.js, src/util/graph/bellmen-ford.js
Initialized starting table with default values for Bellman Ford (yielding table and graph).
Also fixed spelling of Bellman Ford in src/app/graph/bellmen-ford/page.js and src/data/navigation.js
=> Initialized data for Bellman Ford

src/util/graph/floyd-warshall.js
=> init data for floyd warshall

src/app/graph/state-machine/page.js, src/data/navigation.js
navigation.js 
- removed power icon
- removed state machine portion of code
deleted state-machine folder from apps
=> removed state machine

src/app/graph/prims/page.js, src/data/navigation.js
=> Created Prim's page

src/app/graph/kruskals/page.js, src/data/navigation.js, src/util/graph/kruskals.js
=> created kruskals page

src/app/graph/bellmen-ford/page.js, src/util/graph/bellmen-ford.js
* Finished implementing Bellman-Ford algorithm. 
* Optimization: Stops iterating when distances is never updated after one whole iteration.
=> Implemented Bellman-Ford Algorithm

src/components/Graph/GraphAlgorithm.jsx
Implemented functioning replay button minus the styling
=> Implemented functioning replay button

src/components/Graph/GraphAlgorithm.jsx
- Added weighted & directed indicators
- Changed html structure to allow proper alignment of indicators
=> added weighted directed indicators

src/util/graph/dfs.js
=> init data for dfs

src/app/graph/prims/page.js, src/util/graph/bellmen-ford.js, src/util/graph/prims.js
=> Prim's Algorithm Initialized Data

src/components/Graph/GraphAlgorithm.jsx, src/components/algorithm/AlgorithmWrapper.jsx
Added requireStartVertex prop to graph algo, checking if the algorithm requires starting vertex in handlePlay
=> Added prop to Graph Algo

src/components/Graph/GraphAlgorithm.jsx, src/components/Graph/GraphToolbar.jsx
added replay button instead of stepback
=> add graph toolbar

src/components/algorithm/AlgorithmWrapper.jsx
=> Set play to false on generate

src/components/Graph/GraphAlgorithm.jsx
Added directed check w/ allowDirected default value of "true".
=> Add directed check

src/util/graph/kruskals.js
=> added in initial table for kruskals

src/app/graph/dfs/page.js, src/util/graph/dfs.js
Sorry, but idk what i am doing
=> DFS algorithm

.idea/.gitignore, .idea/codeStyles/Project.xml, .idea/codeStyles/codeStyleConfig.xml, .idea/inspectionProfiles/Project_Default.xml, .idea/modules.xml, .idea/r-tools.iml, .idea/vcs.xml, package-lock.json, package.json, src/components/CodeView.jsx
Changed extensions to show correct code syntax highlighting in the example code inside CodeMirror
=> Adjusted syntax highlight

src/util/graph/prims.js
https://github.com/acm-ucr/r-tools/assets/120443522/ca25b5de-5e87-42d7-a5db-23a13d7b3905
* Added Prim's Algorithm
* Have not added any colors or fancy stuff
* The table is not suppose to change for Prim's algorithm sadly
* Maybe could show something like the vertex it is going to jump to or something
* Maybe add colors for already added edges/vertexes & and current edge being processed
=> Added Prim's Algorithm

src/util/graph/floyd-warshall.js
=> current state of Floyd Warshall
